### ISSUE TITLE
Pi/idun cart not booting

### ISSUE THREAD

**Issue by anovaprint** [idun-project/idun-cartridge#9]
Struggling to boot into my idun cartridge and hoping for some assistance. My main questions are what order I should be setting this up in and what I should expect when booting. Also, this is the first board I've assembled on my own so I'm leaning hard towards some type of user error here. I'll try to include pictures in case I've done something horribly wrong (I've got some flux remover in the mail to clean it up a bit better)

I'm using the supplied SD card and the original pi zero w which I understand will want to be powered independently. However I simply get a series of blinking lights on the pi and I never see anything come up on screen. I also tried booting the pi separately without anything attached and get the same result. It ends up with seven blinking lights which is supposedly "kernel not found" but I couldn't tell you if that is accurate or not. Hitting the reset button seems to have no effect

I'm especially curious in what order I should be powering things on. I assume once everything is assembled and inside the 128 I would want to power on the pi first and then power up the 128. I assume I would want to give it a couple of minutes to boot and eventually I would see something on screen on my 128. Does that sound correct? Should I be able to boot the pi independently without anything attached and verify it is at least booting properly?

Also had a bit of a follow-up question on what those partitions should look like on the SD card. Is there anything extra I might need to there? 

I'm probably missing something very silly and appreciate any assistance on what I might be doing wrong here and how I can get going on this project.

Much thanks
![IMG_20231019_112126](https://github.com/idun-project/idun-cartridge/assets/84736206/07193557-3ab6-4d2e-953e-e1cb627706ce)
![IMG_20231019_104451](https://github.com/idun-project/idun-cartridge/assets/84736206/f898306f-8904-4c32-8ba5-58da42554c04)
![IMG_20231019_105146](https://github.com/idun-project/idun-cartridge/assets/84736206/9817c1a1-e6e4-4bb2-9c77-9006fbc5ca30)

**Comment by idun-project** [comment]
Hi. I think the problem is that you are using a Pi Zero W, which is not supported with the latest Linux image. The issues is that the image is for an ARMv7 device, and the original Pi Zero is ARMv6. This will certainly prevent the RPi from booting, as the kernel image is just not compatible.

If you do not have access to another Raspberry Pi, then we can try using an older image for the RPi Zero W. You'll need to download the image from this link and flash it to the SD card using the Raspberry Pi Imager app, or similar: [idunpi_armv6.7z](https://drive.google.com/file/d/1-f4fZqi1PGydYXPUaHLZCb5UNGgmPkZW/view?usp=sharing)

If the above image boots your RPi successfully, then just give it about 10-15 seconds to fully boot, then turn on your Commodore. The Commodore will then show the Idun boot screen, if the cart is working properly.

There may be a path forward for using the original RPi Zero, but only for awhile. The reason I was forced to drop support for it is that upstream Linux providers are dropping it because the Raspberry Pi Foundation has announced it is end-of-life, I believe in 2024. Obviously, they are anxious to move users to the RPi Zero 2.

**Comment by anovaprint** [comment]
Hey, I think that's it! I really appreciate you walking a first time user through it all. 

I have a couple of pi 4s that are locked down on other projects so using the older armv6 image at least tells me the cartridgeassembly seems to have gone as intended.

This will be a good excuse to order the new zero 2 w so I can continue to keep up with the project.

Thank you so much for the help!

![IMG_20231020_114039](https://github.com/idun-project/idun-cartridge/assets/84736206/7d46d8b9-cb09-4834-a23a-201a712314e7)

**Comment by anovaprint** [comment]
I'll let you know if I have any issues with the new pi but I expect it will go smoothly

**Comment by idun-project** [comment]
Happy to help and glad to see that was the problem.

The Pi Zero 2 is a worthwhile upgrade and seems to be the same price; so I guess that is why they are retiring the original Pi Zero.
